// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  identity: __t.identity(),
  roomCode: __t.string().name("room_code"),
  playedAt: __t.timestamp().name("played_at"),
  finalRank: __t.u32().name("final_rank"),
  playerCount: __t.u32().name("player_count"),
  totalScore: __t.u32().name("total_score"),
  avgSimilarity: __t.u32().name("avg_similarity"),
  roundsPlayed: __t.u32().name("rounds_played"),
});
