// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  playerName: __t.string().primaryKey().name("player_name"),
  wins: __t.u32(),
  gamesPlayed: __t.u32().name("games_played"),
  bestScore: __t.u32().name("best_score"),
  updatedAtUs: __t.u64().name("updated_at_us"),
});
