// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  roomCode: __t.string().name("room_code"),
  round: __t.u32(),
  powerupId: __t.string().name("powerup_id"),
  isUsed: __t.bool().name("is_used"),
  hasShield: __t.bool().name("has_shield"),
  hasDoublePoints: __t.bool().name("has_double_points"),
  tokenDrainAmount: __t.u32().name("token_drain_amount"),
  isFrozen: __t.bool().name("is_frozen"),
  frozenUntilMs: __t.u64().name("frozen_until_ms"),
  hintKeywords: __t.string().name("hint_keywords"),
  revealedCategory: __t.string().name("revealed_category"),
});
