// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  roomCode: __t.string().name("room_code"),
  name: __t.string(),
  isReady: __t.bool().name("is_ready"),
  isHost: __t.bool().name("is_host"),
  avatarIndex: __t.u32().name("avatar_index"),
  isOnline: __t.bool().name("is_online"),
  totalScore: __t.u32().name("total_score"),
  roundScores: __t.string().name("round_scores"),
});
