// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  targetIdentity: __t.identity().name("target_identity"),
  roomCode: __t.string().name("room_code"),
  eventType: __t.string().name("event_type"),
  powerupId: __t.string().name("powerup_id"),
  casterName: __t.string().name("caster_name"),
  amount: __t.u32(),
  durationMs: __t.u32().name("duration_ms"),
  hints: __t.string(),
  category: __t.string(),
  difficulty: __t.string(),
});
