// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  code: __t.string().primaryKey(),
  phase: __t.string(),
  hostIdentity: __t.identity().name("host_identity"),
  currentRound: __t.u32().name("current_round"),
  totalRounds: __t.u32().name("total_rounds"),
  currentImageId: __t.string().name("current_image_id"),
  roundStartUs: __t.u64().name("round_start_us"),
  tokenBudget: __t.u32().name("token_budget"),
  roundDurationUs: __t.u64().name("round_duration_us"),
  usedImageIds: __t.string().name("used_image_ids"),
  countdownValue: __t.u32().name("countdown_value"),
  statsRecorded: __t.bool().name("stats_recorded"),
});
