// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  identity: __t.identity(),
  roomCode: __t.string().name("room_code"),
  round: __t.u32(),
  prompt: __t.string(),
  tokensUsed: __t.u32().name("tokens_used"),
  submittedAtUs: __t.u64().name("submitted_at_us"),
  submissionTimeMs: __t.u64().name("submission_time_ms"),
});
