// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CountdownTimer = __t.object("CountdownTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  roomCode: __t.string(),
  tickValue: __t.u32(),
});
export type CountdownTimer = __Infer<typeof CountdownTimer>;

export const GameHistory = __t.object("GameHistory", {
  id: __t.u64(),
  identity: __t.identity(),
  roomCode: __t.string(),
  playedAt: __t.timestamp(),
  finalRank: __t.u32(),
  playerCount: __t.u32(),
  totalScore: __t.u32(),
  avgSimilarity: __t.u32(),
  roundsPlayed: __t.u32(),
});
export type GameHistory = __Infer<typeof GameHistory>;

export const GameTip = __t.object("GameTip", {
  id: __t.u32(),
  text: __t.string(),
});
export type GameTip = __Infer<typeof GameTip>;

export const GlobalLeaderboard = __t.object("GlobalLeaderboard", {
  playerName: __t.string(),
  wins: __t.u32(),
  gamesPlayed: __t.u32(),
  bestScore: __t.u32(),
  updatedAtUs: __t.u64(),
});
export type GlobalLeaderboard = __Infer<typeof GlobalLeaderboard>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  roomCode: __t.string(),
  name: __t.string(),
  isReady: __t.bool(),
  isHost: __t.bool(),
  avatarIndex: __t.u32(),
  isOnline: __t.bool(),
  totalScore: __t.u32(),
  roundScores: __t.string(),
});
export type Player = __Infer<typeof Player>;

export const PlayerPowerup = __t.object("PlayerPowerup", {
  identity: __t.identity(),
  roomCode: __t.string(),
  round: __t.u32(),
  powerupId: __t.string(),
  isUsed: __t.bool(),
  hasShield: __t.bool(),
  hasDoublePoints: __t.bool(),
  tokenDrainAmount: __t.u32(),
  isFrozen: __t.bool(),
  frozenUntilMs: __t.u64(),
  hintKeywords: __t.string(),
  revealedCategory: __t.string(),
});
export type PlayerPowerup = __Infer<typeof PlayerPowerup>;

export const PowerupEvent = __t.object("PowerupEvent", {
  id: __t.u64(),
  targetIdentity: __t.identity(),
  roomCode: __t.string(),
  eventType: __t.string(),
  powerupId: __t.string(),
  casterName: __t.string(),
  amount: __t.u32(),
  durationMs: __t.u32(),
  hints: __t.string(),
  category: __t.string(),
  difficulty: __t.string(),
});
export type PowerupEvent = __Infer<typeof PowerupEvent>;

export const Room = __t.object("Room", {
  code: __t.string(),
  phase: __t.string(),
  hostIdentity: __t.identity(),
  currentRound: __t.u32(),
  totalRounds: __t.u32(),
  currentImageId: __t.string(),
  roundStartUs: __t.u64(),
  tokenBudget: __t.u32(),
  usedImageIds: __t.string(),
  countdownValue: __t.u32(),
  statsRecorded: __t.bool(),
});
export type Room = __Infer<typeof Room>;

export const RoundEndTimer = __t.object("RoundEndTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  roomCode: __t.string(),
  round: __t.u32(),
});
export type RoundEndTimer = __Infer<typeof RoundEndTimer>;

export const RoundResult = __t.object("RoundResult", {
  id: __t.u64(),
  identity: __t.identity(),
  roomCode: __t.string(),
  round: __t.u32(),
  playerName: __t.string(),
  avatarIndex: __t.u32(),
  prompt: __t.string(),
  imageData: __t.string(),
  tokensUsed: __t.u32(),
  similarityScore: __t.u32(),
  roundScore: __t.u32(),
  placement: __t.u32(),
  reasoning: __t.string(),
  scoreBreakdown: __t.string(),
  hadDoublePoints: __t.bool(),
  simScore: __t.u32(),
  effScore: __t.u32(),
  speedScore: __t.u32(),
});
export type RoundResult = __Infer<typeof RoundResult>;

export const RoundStartTimer = __t.object("RoundStartTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  roomCode: __t.string(),
  round: __t.u32(),
});
export type RoundStartTimer = __Infer<typeof RoundStartTimer>;

export const Submission = __t.object("Submission", {
  id: __t.u64(),
  identity: __t.identity(),
  roomCode: __t.string(),
  round: __t.u32(),
  prompt: __t.string(),
  tokensUsed: __t.u32(),
  submittedAtUs: __t.u64(),
  submissionTimeMs: __t.u64(),
});
export type Submission = __Infer<typeof Submission>;

export const UserProfile = __t.object("UserProfile", {
  identity: __t.identity(),
  displayName: __t.string(),
  displayNameLower: __t.string(),
  avatarId: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type UserProfile = __Infer<typeof UserProfile>;

export const UserStats = __t.object("UserStats", {
  identity: __t.identity(),
  gamesPlayed: __t.u32(),
  gamesWon: __t.u32(),
  totalScore: __t.u64(),
  bestScore: __t.u32(),
  totalSimilarity: __t.u64(),
  totalTokens: __t.u64(),
  totalRounds: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type UserStats = __Infer<typeof UserStats>;

