// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  gamesPlayed: __t.u32().name("games_played"),
  gamesWon: __t.u32().name("games_won"),
  totalScore: __t.u64().name("total_score"),
  bestScore: __t.u32().name("best_score"),
  totalSimilarity: __t.u64().name("total_similarity"),
  totalTokens: __t.u64().name("total_tokens"),
  totalRounds: __t.u32().name("total_rounds"),
  updatedAt: __t.timestamp().name("updated_at"),
});
