// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateRoomReducer from "../create_room_reducer";
import JoinRoomReducer from "../join_room_reducer";
import NextRoundReducer from "../next_round_reducer";
import PlayAgainReducer from "../play_again_reducer";
import StartGameReducer from "../start_game_reducer";
import SubmitPromptReducer from "../submit_prompt_reducer";
import SubmitScoreReducer from "../submit_score_reducer";
import ToggleReadyReducer from "../toggle_ready_reducer";
import UsePowerupReducer from "../use_powerup_reducer";

export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type NextRoundParams = __Infer<typeof NextRoundReducer>;
export type PlayAgainParams = __Infer<typeof PlayAgainReducer>;
export type StartGameParams = __Infer<typeof StartGameReducer>;
export type SubmitPromptParams = __Infer<typeof SubmitPromptReducer>;
export type SubmitScoreParams = __Infer<typeof SubmitScoreReducer>;
export type ToggleReadyParams = __Infer<typeof ToggleReadyReducer>;
export type UsePowerupParams = __Infer<typeof UsePowerupReducer>;

